version: "3.8"

services:
  psql:
    build: 
      context: ./db
      dockerfile: ../psql.Dockerfile
    volumes: 
      - psql-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports: 
      - 5432:5432
    env_file:
      - .env
    networks: 
      - backend

  app: 
    build: 
      context: ./backend
      dockerfile: ../app.Dockerfile
    command: 
      - /bin/bash
      - -c
      - |
        ./app/prestart.sh
        uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes: 
      - ./backend:/usr/src/app
    ports: 
      - 8000:8000
    env_file:
      - .env
    networks: 
      - backend
      - frontend
    depends_on:
      - psql

networks:
  frontend:
  backend:
    
volumes:
  psql-data: